on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Staging
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          tags: ghcr.io/checksumdev/lumen:nightly
          push: ${{ github.event_name == 'push' }}
          file: ./Dockerfile
          context: .
